### ISSUE TITLE
:link pseudo-selector doesn't seem to work

### ISSUE THREAD

**Issue by hrj** [UprootLabs/gngr#151]
In a page generate by javadoc, the links are always supposed to be in bold. They define this rule:
```css
td.colOne a:link, td.colOne a:active, td.colOne a:visited, td.colOne a:hover,
td.colFirst a:link, td.colFirst a:active, td.colFirst a:visited, td.colFirst a:hover,
td.colLast a:link, td.colLast a:active, td.colLast a:visited, td.colLast a:hover {
    font-weight: bold;
}
```
But the bold weight is being selected only for hovered links. According to spec, the `:link` selector should select unvisited links.

Interestingly, the spec itself considers the issue of privacy for `:link` selectors:
> Note. It is possible for style sheet authors to abuse the :link and :visited pseudo-classes to determine which sites a user has visited without the user's consent. UAs may therefore treat all links as unvisited links, or implement other measures to preserve the user's privacy while rendering visited and unvisited links differently. See [P3P] for more information about handling privacy.
